name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup toolchain
      run: |
        apt-get update
        apt-get install -y gcc-arm-none-eabi
        arm-none-eabi-gcc --version
    
    - name: Build uf2
      run: |
        make uf2
    - name: Create timestamp
      run: echo "Timestamp: $(date +'%Y-%m-%d %H:%M:%S')" > bin/timestamp.txt    

    - name: Deploy uf2
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: bin
        extra_files: timestamp.txt

