name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup toolchain
      run: |
        apt-get update
        apt-get install -y gcc-arm-none-eabi
        arm-none-eabi-gcc --version
    
    - name: Build uf2
      run: |
        make uf2
    
    - name: Push to GitHub
      uses: ad-m/github-push-action@v0.8.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
        tags: true
